#Init BIND-server service
---
- name: "{{ bind_service_name }} service config on host"
  template:
    src: systemd/bind.service.j2
    dest: "/etc/systemd/system/{{ bind_service_name }}.service"
    backup: yes
  notify: "{{ bind_service_name }} working dir creation"
