---
- name: "Installation {{ bind_service_name }}"
  become: yes
  become_user: root
  include: install.yml

- name: "Unistallation {{ bind_service_name }}"
  become: yes
  become_user: root
  include: uninstall.yml
  when: uninstall_service | bool