#Remove BIND-server service
---
- name: "Stop {{ bind_service_name }}"
  service:
    name: "{{ bind_service_name }}"
    enabled: no
    state: stopped
  ignore_errors: yes

- name: "Remove /etc/systemd/system/{{ bind_service_name }}.service"
  file:
    path: "/etc/systemd/system/{{ bind_service_name }}.service"
    state: absent
  notify: "{{ bind_service_name }} restart uninstall"
